name: Build, Release, and Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rulekeeper-bot:latest

  binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt pyinstaller python-dotenv

      # - name: Build binary
      #   run: |
      #     pyinstaller --onefile --name rulekeeper-bot main.py

      # macOS: Build .dmg
      - name: Build .dmg on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install create-dmg
          mkdir -p dist/dmg-root
          cp dist/rulekeeper-bot dist/dmg-root/
          rm -f dist/rulekeeper-bot.dmg
          create-dmg dist/rulekeeper-bot.dmg dist/dmg-root

      # Linux: Build AppImage and deb
      - name: Build AppImage and deb
        if: matrix.os == 'ubuntu-latest'
        run: |
          # Update package list and install dependencies
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev build-essential libffi-dev wget squashfs-tools desktop-file-utils imagemagick

          # Install fpm
          sudo gem install --no-document fpm

          # Download and extract non-AppImage version of appimagetool
          wget https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          ./appimagetool-x86_64.AppImage --appimage-extract

          # Move appimagetool binary to system path
          sudo mv squashfs-root/usr/bin/appimagetool /usr/local/bin/appimagetool
          sudo chmod +x /usr/local/bin/appimagetool

          # Fix missing mksquashfs by symlinking system-wide version to expected path
          if [ ! -f /usr/local/lib/appimagekit/mksquashfs ]; then
            sudo mkdir -p /usr/local/lib/appimagekit
            sudo ln -s "$(which mksquashfs)" /usr/local/lib/appimagekit/mksquashfs
          fi

          # Build AppImage and .deb package
          mkdir -p AppDir/usr/bin

          # Copy binary
          cp dist/rulekeeper-bot AppDir/usr/bin/
          
          # Copy icon
          convert web/static/images/icon.png -resize 256x256 AppDir/rulekeeper-bot.png

          # Create .desktop file (No icon for now, add it later)
          cat <<EOF > AppDir/rulekeeper-bot.desktop
          [Desktop Entry]
          Name=RuleKeeper Bot
          Exec=rulekeeper-bot
          Icon=rulekeeper-bot
          Type=Application
          Categories=Utility;
          EOF

          chmod +x AppDir/rulekeeper-bot.desktop

          # Run appimagetool
          (cd AppDir && /usr/local/bin/appimagetool . ../rulekeeper-bot.AppImage)

          # Build .deb package
          fpm -s dir -t deb -n rulekeeper-bot -v 1.0.0 dist/rulekeeper-bot=/usr/bin/rulekeeper-bot

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: rulekeeper-bot-${{ matrix.os }}
          path: |
            dist/*.dmg
            rulekeeper-bot.AppImage
            *.deb

  release:
    needs: binaries
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Delete old continuous release (if exists)
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: continuous
          github_token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Create new continuous release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: continuous
          name: Continuous Release
          body: "Latest build of rulekeeper-bot for all platforms."
          files: ./artifacts/**/*
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
